image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  #only:
  #  - master

.test:
  image: python:3.8.5
  stage: test

  before_script:
    - cd backend
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements_dev.txt
    - python manage.py migrate
    - cd ..

unit-test:
  extends: .test
  script:
    - cd backend
    - python manage.py test
    - BACKEND_RET=$?
    - exit $BACKEND_RET
  after_script:


deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master
