# coding: utf-8

"""
    站点内AP增值服务配置

    站点内AP增值服务配置北向接口，主要特性： * 查询站点内AP增值服务配置。 * 修改站点内AP增值服务配置。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApExtraServiceInputDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mu': 'bool',
        'server_ip': 'str',
        'server_port': 'int',
        'interver': 'int',
        'rssi': 'int',
        'ap_location_enable': 'bool',
        'ap_location': 'str',
        'enable_psk': 'bool'
    }

    attribute_map = {
        'mu': 'mu',
        'server_ip': 'serverIp',
        'server_port': 'serverPort',
        'interver': 'interver',
        'rssi': 'rssi',
        'ap_location_enable': 'apLocationEnable',
        'ap_location': 'apLocation',
        'enable_psk': 'enablePsk'
    }

    def __init__(self, mu=None, server_ip=None, server_port=None, interver=None, rssi=None, ap_location_enable=None, ap_location=None, enable_psk=None):
        """
        ApExtraServiceInputDto - a model defined in Swagger
        """

        self._mu = None
        self._server_ip = None
        self._server_port = None
        self._interver = None
        self._rssi = None
        self._ap_location_enable = None
        self._ap_location = None
        self._enable_psk = None

        if mu is not None:
          self.mu = mu
        if server_ip is not None:
          self.server_ip = server_ip
        if server_port is not None:
          self.server_port = server_port
        if interver is not None:
          self.interver = interver
        if rssi is not None:
          self.rssi = rssi
        if ap_location_enable is not None:
          self.ap_location_enable = ap_location_enable
        if ap_location is not None:
          self.ap_location = ap_location
        if enable_psk is not None:
          self.enable_psk = enable_psk

    @property
    def mu(self):
        """
        Gets the mu of this ApExtraServiceInputDto.
        是否开启上传功能，将终端位置信息上报到指定服务器。

        :return: The mu of this ApExtraServiceInputDto.
        :rtype: bool
        """
        return self._mu

    @mu.setter
    def mu(self, mu):
        """
        Sets the mu of this ApExtraServiceInputDto.
        是否开启上传功能，将终端位置信息上报到指定服务器。

        :param mu: The mu of this ApExtraServiceInputDto.
        :type: bool
        """

        self._mu = mu

    @property
    def server_ip(self):
        """
        Gets the server_ip of this ApExtraServiceInputDto.
        服务器IP/域名。当mu为true时，serverIp必填。

        :return: The server_ip of this ApExtraServiceInputDto.
        :rtype: str
        """
        return self._server_ip

    @server_ip.setter
    def server_ip(self, server_ip):
        """
        Sets the server_ip of this ApExtraServiceInputDto.
        服务器IP/域名。当mu为true时，serverIp必填。

        :param server_ip: The server_ip of this ApExtraServiceInputDto.
        :type: str
        """

        self._server_ip = server_ip

    @property
    def server_port(self):
        """
        Gets the server_port of this ApExtraServiceInputDto.
        端口号，必须为1-65535范围内的整数，不填默认为10031。端口号跟服务器IP/域名要么都填，要么都不填。

        :return: The server_port of this ApExtraServiceInputDto.
        :rtype: int
        """
        return self._server_port

    @server_port.setter
    def server_port(self, server_port):
        """
        Sets the server_port of this ApExtraServiceInputDto.
        端口号，必须为1-65535范围内的整数，不填默认为10031。端口号跟服务器IP/域名要么都填，要么都不填。

        :param server_port: The server_port of this ApExtraServiceInputDto.
        :type: int
        """
        if server_port is not None and server_port > 65535:
            raise ValueError("Invalid value for `server_port`, must be a value less than or equal to `65535`")
        if server_port is not None and server_port < 1:
            raise ValueError("Invalid value for `server_port`, must be a value greater than or equal to `1`")

        self._server_port = server_port

    @property
    def interver(self):
        """
        Gets the interver of this ApExtraServiceInputDto.
        上报周期，单位为ms，必须是500-60000范围内的整数，不填默认为20000。

        :return: The interver of this ApExtraServiceInputDto.
        :rtype: int
        """
        return self._interver

    @interver.setter
    def interver(self, interver):
        """
        Sets the interver of this ApExtraServiceInputDto.
        上报周期，单位为ms，必须是500-60000范围内的整数，不填默认为20000。

        :param interver: The interver of this ApExtraServiceInputDto.
        :type: int
        """
        if interver is not None and interver > 60000:
            raise ValueError("Invalid value for `interver`, must be a value less than or equal to `60000`")
        if interver is not None and interver < 500:
            raise ValueError("Invalid value for `interver`, must be a value greater than or equal to `500`")

        self._interver = interver

    @property
    def rssi(self):
        """
        Gets the rssi of this ApExtraServiceInputDto.
        阀值，必须为-95-0范围内的整数，不填默认为-75。

        :return: The rssi of this ApExtraServiceInputDto.
        :rtype: int
        """
        return self._rssi

    @rssi.setter
    def rssi(self, rssi):
        """
        Sets the rssi of this ApExtraServiceInputDto.
        阀值，必须为-95-0范围内的整数，不填默认为-75。

        :param rssi: The rssi of this ApExtraServiceInputDto.
        :type: int
        """
        self._rssi = rssi

    @property
    def ap_location_enable(self):
        """
        Gets the ap_location_enable of this ApExtraServiceInputDto.
        用于标识AP安装位置信息开关是否打开。

        :return: The ap_location_enable of this ApExtraServiceInputDto.
        :rtype: bool
        """
        return self._ap_location_enable

    @ap_location_enable.setter
    def ap_location_enable(self, ap_location_enable):
        """
        Sets the ap_location_enable of this ApExtraServiceInputDto.
        用于标识AP安装位置信息开关是否打开。

        :param ap_location_enable: The ap_location_enable of this ApExtraServiceInputDto.
        :type: bool
        """

        self._ap_location_enable = ap_location_enable

    @property
    def ap_location(self):
        """
        Gets the ap_location of this ApExtraServiceInputDto.
        AP安装位置信息。当apLocationEnable为true时，apLocation必填。

        :return: The ap_location of this ApExtraServiceInputDto.
        :rtype: str
        """
        return self._ap_location

    @ap_location.setter
    def ap_location(self, ap_location):
        """
        Sets the ap_location of this ApExtraServiceInputDto.
        AP安装位置信息。当apLocationEnable为true时，apLocation必填。

        :param ap_location: The ap_location of this ApExtraServiceInputDto.
        :type: str
        """
        if ap_location is not None and len(ap_location) > 63:
            raise ValueError("Invalid value for `ap_location`, length must be less than or equal to `63`")
        if ap_location is not None and len(ap_location) < 1:
            raise ValueError("Invalid value for `ap_location`, length must be greater than or equal to `1`")
        if ap_location is not None and not re.search('[a-zA-Z0-9\\x5f\\x2d\\x40\\x2e]{1,}', ap_location):
            raise ValueError("Invalid value for `ap_location`, must be a follow pattern or equal to `/[a-zA-Z0-9\\x5f\\x2d\\x40\\x2e]{1,}/`")

        self._ap_location = ap_location

    @property
    def enable_psk(self):
        """
        Gets the enable_psk of this ApExtraServiceInputDto.
        PSK使能。

        :return: The enable_psk of this ApExtraServiceInputDto.
        :rtype: bool
        """
        return self._enable_psk

    @enable_psk.setter
    def enable_psk(self, enable_psk):
        """
        Sets the enable_psk of this ApExtraServiceInputDto.
        PSK使能。

        :param enable_psk: The enable_psk of this ApExtraServiceInputDto.
        :type: bool
        """

        self._enable_psk = enable_psk

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApExtraServiceInputDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
