# coding: utf-8

"""
    防火墙ASPF配置

    防火墙配置ASPF第三方接口，主要特性： · 查询ASPF配置 · 修改ASPF配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AspfConfigDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aspf_list': 'list[str]'
    }

    attribute_map = {
        'aspf_list': 'aspfList'
    }

    def __init__(self, aspf_list=None):
        """
        AspfConfigDto - a model defined in Swagger
        """

        self._aspf_list = None

        if aspf_list is not None:
          self.aspf_list = aspf_list

    @property
    def aspf_list(self):
        """
        Gets the aspf_list of this AspfConfigDto.
        ASPF可配置协议集合：默认为空，可选“dns”、“ftp”、“h323”、“icq”、“ils”、“mms”、“msn”、“netbios”、“pptp”、“qq”、“rsh”、“rtsp”、“sccp”、“sip”或者“sqlnet”中的一个或多个协议。

        :return: The aspf_list of this AspfConfigDto.
        :rtype: list[str]
        """
        return self._aspf_list

    @aspf_list.setter
    def aspf_list(self, aspf_list):
        """
        Sets the aspf_list of this AspfConfigDto.
        ASPF可配置协议集合：默认为空，可选“dns”、“ftp”、“h323”、“icq”、“ils”、“mms”、“msn”、“netbios”、“pptp”、“qq”、“rsh”、“rtsp”、“sccp”、“sip”或者“sqlnet”中的一个或多个协议。

        :param aspf_list: The aspf_list of this AspfConfigDto.
        :type: list[str]
        """

        self._aspf_list = aspf_list

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AspfConfigDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
