# coding: utf-8

"""
    终端用户管理

    终端用户管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CutUserInputDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'third_user_infos': 'list[ThirdUserInfoData]'
    }

    attribute_map = {
        'third_user_infos': 'thirdUserInfos'
    }

    def __init__(self, third_user_infos=None):
        """
        CutUserInputDto - a model defined in Swagger
        """

        self._third_user_infos = None

        if third_user_infos is not None:
          self.third_user_infos = third_user_infos

    @property
    def third_user_infos(self):
        """
        Gets the third_user_infos of this CutUserInputDto.

        :return: The third_user_infos of this CutUserInputDto.
        :rtype: list[ThirdUserInfoData]
        """
        return self._third_user_infos

    @third_user_infos.setter
    def third_user_infos(self, third_user_infos):
        """
        Sets the third_user_infos of this CutUserInputDto.

        :param third_user_infos: The third_user_infos of this CutUserInputDto.
        :type: list[ThirdUserInfoData]
        """

        self._third_user_infos = third_user_infos

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CutUserInputDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
