# coding: utf-8

"""
    网络设备管理

    提供北向查询网络设备服务。 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NeListOpenApiResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'int',
        'description': 'str',
        'data': 'list[NeDetailInfo]'
    }

    attribute_map = {
        'code': 'code',
        'description': 'description',
        'data': 'data'
    }

    def __init__(self, code=None, description=None, data=None):
        """
        NeListOpenApiResponse - a model defined in Swagger
        """

        self._code = None
        self._description = None
        self._data = None

        if code is not None:
          self.code = code
        if description is not None:
          self.description = description
        if data is not None:
          self.data = data

    @property
    def code(self):
        """
        Gets the code of this NeListOpenApiResponse.
        操作返回码。可以是如下值之一： 0：成功 非0：失败 

        :return: The code of this NeListOpenApiResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this NeListOpenApiResponse.
        操作返回码。可以是如下值之一： 0：成功 非0：失败 

        :param code: The code of this NeListOpenApiResponse.
        :type: int
        """

        self._code = code

    @property
    def description(self):
        """
        Gets the description of this NeListOpenApiResponse.
        接口调用结果的描述信息

        :return: The description of this NeListOpenApiResponse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this NeListOpenApiResponse.
        接口调用结果的描述信息

        :param description: The description of this NeListOpenApiResponse.
        :type: str
        """

        self._description = description

    @property
    def data(self):
        """
        Gets the data of this NeListOpenApiResponse.

        :return: The data of this NeListOpenApiResponse.
        :rtype: list[NeDetailInfo]
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this NeListOpenApiResponse.

        :param data: The data of this NeListOpenApiResponse.
        :type: list[NeDetailInfo]
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NeListOpenApiResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
