# coding: utf-8

"""
    CIS服务接口

    CIS操作接口说明： 1、创建CIS隔离 2、创建CIS阻断 3、撤销CIS阻断/隔离 4、阻断隔离应用状态查询 5、CIS策略命中率查询 

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PolicyHitsDTO(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_date': 'str',
        'end_date': 'str',
        'producer': 'str',
        'block_ids': 'list[str]',
        'policy_names': 'list[str]'
    }

    attribute_map = {
        'start_date': 'startDate',
        'end_date': 'endDate',
        'producer': 'producer',
        'block_ids': 'blockIds',
        'policy_names': 'policyNames'
    }

    def __init__(self, start_date=None, end_date=None, producer=None, block_ids=None, policy_names=None):
        """
        PolicyHitsDTO - a model defined in Swagger
        """

        self._start_date = None
        self._end_date = None
        self._producer = None
        self._block_ids = None
        self._policy_names = None

        if start_date is not None:
          self.start_date = start_date
        if end_date is not None:
          self.end_date = end_date
        if producer is not None:
          self.producer = producer
        if block_ids is not None:
          self.block_ids = block_ids
        if policy_names is not None:
          self.policy_names = policy_names

    @property
    def start_date(self):
        """
        Gets the start_date of this PolicyHitsDTO.
        开始日期，非空时要求是合法的日期格式；如果开始日期和结束日期同时为空，默认查过去一个月的数据，yyyy-MM-dd HH:mm:ss。

        :return: The start_date of this PolicyHitsDTO.
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """
        Sets the start_date of this PolicyHitsDTO.
        开始日期，非空时要求是合法的日期格式；如果开始日期和结束日期同时为空，默认查过去一个月的数据，yyyy-MM-dd HH:mm:ss。

        :param start_date: The start_date of this PolicyHitsDTO.
        :type: str
        """
        if start_date is not None and len(start_date) > 19:
            raise ValueError("Invalid value for `start_date`, length must be less than or equal to `19`")
        if start_date is not None and len(start_date) < 19:
            raise ValueError("Invalid value for `start_date`, length must be greater than or equal to `19`")

        self._start_date = start_date

    @property
    def end_date(self):
        """
        Gets the end_date of this PolicyHitsDTO.
        结束日期，非空时要求是合法的日期格式；如果开始日期和结束日期同时为空，默认查过去一个月的数据，yyyy-MM-dd HH:mm:ss。

        :return: The end_date of this PolicyHitsDTO.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """
        Sets the end_date of this PolicyHitsDTO.
        结束日期，非空时要求是合法的日期格式；如果开始日期和结束日期同时为空，默认查过去一个月的数据，yyyy-MM-dd HH:mm:ss。

        :param end_date: The end_date of this PolicyHitsDTO.
        :type: str
        """
        if end_date is not None and len(end_date) > 19:
            raise ValueError("Invalid value for `end_date`, length must be less than or equal to `19`")
        if end_date is not None and len(end_date) < 19:
            raise ValueError("Invalid value for `end_date`, length must be greater than or equal to `19`")

        self._end_date = end_date

    @property
    def producer(self):
        """
        Gets the producer of this PolicyHitsDTO.
        调用者。

        :return: The producer of this PolicyHitsDTO.
        :rtype: str
        """
        return self._producer

    @producer.setter
    def producer(self, producer):
        """
        Sets the producer of this PolicyHitsDTO.
        调用者。

        :param producer: The producer of this PolicyHitsDTO.
        :type: str
        """
        if producer is not None and len(producer) > 10:
            raise ValueError("Invalid value for `producer`, length must be less than or equal to `10`")

        self._producer = producer

    @property
    def block_ids(self):
        """
        Gets the block_ids of this PolicyHitsDTO.
        事件ID列表，UUID格式；Campus融合场景，blockIds为必填字段；DCN融合场景，blockIds和policyNames不可同时为空，都传的情况下，以blockIds为准。

        :return: The block_ids of this PolicyHitsDTO.
        :rtype: list[str]
        """
        return self._block_ids

    @block_ids.setter
    def block_ids(self, block_ids):
        """
        Sets the block_ids of this PolicyHitsDTO.
        事件ID列表，UUID格式；Campus融合场景，blockIds为必填字段；DCN融合场景，blockIds和policyNames不可同时为空，都传的情况下，以blockIds为准。

        :param block_ids: The block_ids of this PolicyHitsDTO.
        :type: list[str]
        """

        self._block_ids = block_ids

    @property
    def policy_names(self):
        """
        Gets the policy_names of this PolicyHitsDTO.
        策略名称。Campus融合，该字段没有业务上的意义，不需要填写；DCN融合场景，blockIds和policyNames不可同时为空，都传的情况下，以blockIds为准。

        :return: The policy_names of this PolicyHitsDTO.
        :rtype: list[str]
        """
        return self._policy_names

    @policy_names.setter
    def policy_names(self, policy_names):
        """
        Sets the policy_names of this PolicyHitsDTO.
        策略名称。Campus融合，该字段没有业务上的意义，不需要填写；DCN融合场景，blockIds和policyNames不可同时为空，都传的情况下，以blockIds为准。

        :param policy_names: The policy_names of this PolicyHitsDTO.
        :type: list[str]
        """

        self._policy_names = policy_names

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PolicyHitsDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
