# coding: utf-8

"""
    设备出厂设置恢复

    设备恢复出厂设置第三方接口。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ResetDeviceFailedDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_id': 'str',
        'esn': 'str',
        'errmsg': 'str',
        'errcode': 'str'
    }

    attribute_map = {
        'device_id': 'deviceId',
        'esn': 'esn',
        'errmsg': 'errmsg',
        'errcode': 'errcode'
    }

    def __init__(self, device_id=None, esn=None, errmsg=None, errcode=None):
        """
        ResetDeviceFailedDto - a model defined in Swagger
        """

        self._device_id = None
        self._esn = None
        self._errmsg = None
        self._errcode = None

        if device_id is not None:
          self.device_id = device_id
        if esn is not None:
          self.esn = esn
        if errmsg is not None:
          self.errmsg = errmsg
        if errcode is not None:
          self.errcode = errcode

    @property
    def device_id(self):
        """
        Gets the device_id of this ResetDeviceFailedDto.
        设备ID。

        :return: The device_id of this ResetDeviceFailedDto.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """
        Sets the device_id of this ResetDeviceFailedDto.
        设备ID。

        :param device_id: The device_id of this ResetDeviceFailedDto.
        :type: str
        """

        self._device_id = device_id

    @property
    def esn(self):
        """
        Gets the esn of this ResetDeviceFailedDto.
        设备ESN号。

        :return: The esn of this ResetDeviceFailedDto.
        :rtype: str
        """
        return self._esn

    @esn.setter
    def esn(self, esn):
        """
        Sets the esn of this ResetDeviceFailedDto.
        设备ESN号。

        :param esn: The esn of this ResetDeviceFailedDto.
        :type: str
        """

        self._esn = esn

    @property
    def errmsg(self):
        """
        Gets the errmsg of this ResetDeviceFailedDto.
        设备恢复出厂设置失败错误信息。

        :return: The errmsg of this ResetDeviceFailedDto.
        :rtype: str
        """
        return self._errmsg

    @errmsg.setter
    def errmsg(self, errmsg):
        """
        Sets the errmsg of this ResetDeviceFailedDto.
        设备恢复出厂设置失败错误信息。

        :param errmsg: The errmsg of this ResetDeviceFailedDto.
        :type: str
        """

        self._errmsg = errmsg

    @property
    def errcode(self):
        """
        Gets the errcode of this ResetDeviceFailedDto.
        设备恢复出厂设置失败错误码。

        :return: The errcode of this ResetDeviceFailedDto.
        :rtype: str
        """
        return self._errcode

    @errcode.setter
    def errcode(self, errcode):
        """
        Sets the errcode of this ResetDeviceFailedDto.
        设备恢复出厂设置失败错误码。

        :param errcode: The errcode of this ResetDeviceFailedDto.
        :type: str
        """

        self._errcode = errcode

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ResetDeviceFailedDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
