# coding: utf-8

"""
    站点模板管理

    站点模板第三方接口说明。 

    OpenAPI spec version: 1.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SiteTempResponseDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'types': 'list[str]',
        'custom': 'bool',
        'config_identifies': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'types': 'types',
        'custom': 'custom',
        'config_identifies': 'configIdentifies'
    }

    def __init__(self, id=None, name=None, types=None, custom=None, config_identifies=None):
        """
        SiteTempResponseDto - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._types = None
        self._custom = None
        self._config_identifies = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if types is not None:
          self.types = types
        if custom is not None:
          self.custom = custom
        if config_identifies is not None:
          self.config_identifies = config_identifies

    @property
    def id(self):
        """
        Gets the id of this SiteTempResponseDto.
        站点模板ID，UUID格式。

        :return: The id of this SiteTempResponseDto.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SiteTempResponseDto.
        站点模板ID，UUID格式。

        :param id: The id of this SiteTempResponseDto.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this SiteTempResponseDto.
        站点模板名称。

        :return: The name of this SiteTempResponseDto.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SiteTempResponseDto.
        站点模板名称。

        :param name: The name of this SiteTempResponseDto.
        :type: str
        """

        self._name = name

    @property
    def types(self):
        """
        Gets the types of this SiteTempResponseDto.
        站点模板类型列表。

        :return: The types of this SiteTempResponseDto.
        :rtype: list[str]
        """
        return self._types

    @types.setter
    def types(self, types):
        """
        Sets the types of this SiteTempResponseDto.
        站点模板类型列表。

        :param types: The types of this SiteTempResponseDto.
        :type: list[str]
        """

        self._types = types

    @property
    def custom(self):
        """
        Gets the custom of this SiteTempResponseDto.
        是否定制特性。

        :return: The custom of this SiteTempResponseDto.
        :rtype: bool
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """
        Sets the custom of this SiteTempResponseDto.
        是否定制特性。

        :param custom: The custom of this SiteTempResponseDto.
        :type: bool
        """

        self._custom = custom

    @property
    def config_identifies(self):
        """
        Gets the config_identifies of this SiteTempResponseDto.
        支持定制的特性集合，字符串格式，以，分隔

        :return: The config_identifies of this SiteTempResponseDto.
        :rtype: str
        """
        return self._config_identifies

    @config_identifies.setter
    def config_identifies(self, config_identifies):
        """
        Sets the config_identifies of this SiteTempResponseDto.
        支持定制的特性集合，字符串格式，以，分隔

        :param config_identifies: The config_identifies of this SiteTempResponseDto.
        :type: str
        """

        self._config_identifies = config_identifies

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SiteTempResponseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
