# coding: utf-8

"""
    用户流量信息查询

    控制器支持查询指定时间内流量和时长发生变化的用户流量信息分页查询北向接口。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TimeFlowStDetailInfosOutputDto(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'site_id': 'str',
        'user_name': 'str',
        'last_charge_time': 'str',
        'used_flow': 'str',
        'used_time': 'str',
        'policy_flow': 'str',
        'policy_time': 'str',
        'remain_flow': 'str',
        'remain_time': 'str'
    }

    attribute_map = {
        'id': 'id',
        'site_id': 'siteId',
        'user_name': 'userName',
        'last_charge_time': 'lastChargeTime',
        'used_flow': 'usedFlow',
        'used_time': 'usedTime',
        'policy_flow': 'policyFlow',
        'policy_time': 'policyTime',
        'remain_flow': 'remainFlow',
        'remain_time': 'remainTime'
    }

    def __init__(self, id=None, site_id=None, user_name=None, last_charge_time=None, used_flow=None, used_time=None, policy_flow=None, policy_time=None, remain_flow=None, remain_time=None):
        """
        TimeFlowStDetailInfosOutputDto - a model defined in Swagger
        """

        self._id = None
        self._site_id = None
        self._user_name = None
        self._last_charge_time = None
        self._used_flow = None
        self._used_time = None
        self._policy_flow = None
        self._policy_time = None
        self._remain_flow = None
        self._remain_time = None

        if id is not None:
          self.id = id
        if site_id is not None:
          self.site_id = site_id
        if user_name is not None:
          self.user_name = user_name
        if last_charge_time is not None:
          self.last_charge_time = last_charge_time
        if used_flow is not None:
          self.used_flow = used_flow
        if used_time is not None:
          self.used_time = used_time
        if policy_flow is not None:
          self.policy_flow = policy_flow
        if policy_time is not None:
          self.policy_time = policy_time
        if remain_flow is not None:
          self.remain_flow = remain_flow
        if remain_time is not None:
          self.remain_time = remain_time

    @property
    def id(self):
        """
        Gets the id of this TimeFlowStDetailInfosOutputDto.
        流量时长ID。

        :return: The id of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TimeFlowStDetailInfosOutputDto.
        流量时长ID。

        :param id: The id of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._id = id

    @property
    def site_id(self):
        """
        Gets the site_id of this TimeFlowStDetailInfosOutputDto.
        站点ID。

        :return: The site_id of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        """
        Sets the site_id of this TimeFlowStDetailInfosOutputDto.
        站点ID。

        :param site_id: The site_id of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._site_id = site_id

    @property
    def user_name(self):
        """
        Gets the user_name of this TimeFlowStDetailInfosOutputDto.
        账号名。

        :return: The user_name of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """
        Sets the user_name of this TimeFlowStDetailInfosOutputDto.
        账号名。

        :param user_name: The user_name of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._user_name = user_name

    @property
    def last_charge_time(self):
        """
        Gets the last_charge_time of this TimeFlowStDetailInfosOutputDto.
        最后一次计费更新时间。

        :return: The last_charge_time of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._last_charge_time

    @last_charge_time.setter
    def last_charge_time(self, last_charge_time):
        """
        Sets the last_charge_time of this TimeFlowStDetailInfosOutputDto.
        最后一次计费更新时间。

        :param last_charge_time: The last_charge_time of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._last_charge_time = last_charge_time

    @property
    def used_flow(self):
        """
        Gets the used_flow of this TimeFlowStDetailInfosOutputDto.
        已使用流量（兆）。

        :return: The used_flow of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._used_flow

    @used_flow.setter
    def used_flow(self, used_flow):
        """
        Sets the used_flow of this TimeFlowStDetailInfosOutputDto.
        已使用流量（兆）。

        :param used_flow: The used_flow of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._used_flow = used_flow

    @property
    def used_time(self):
        """
        Gets the used_time of this TimeFlowStDetailInfosOutputDto.
        已使用时间（分钟）。

        :return: The used_time of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._used_time

    @used_time.setter
    def used_time(self, used_time):
        """
        Sets the used_time of this TimeFlowStDetailInfosOutputDto.
        已使用时间（分钟）。

        :param used_time: The used_time of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._used_time = used_time

    @property
    def policy_flow(self):
        """
        Gets the policy_flow of this TimeFlowStDetailInfosOutputDto.
        策略流量（兆）。

        :return: The policy_flow of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._policy_flow

    @policy_flow.setter
    def policy_flow(self, policy_flow):
        """
        Sets the policy_flow of this TimeFlowStDetailInfosOutputDto.
        策略流量（兆）。

        :param policy_flow: The policy_flow of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._policy_flow = policy_flow

    @property
    def policy_time(self):
        """
        Gets the policy_time of this TimeFlowStDetailInfosOutputDto.
        策略时长（分钟）。

        :return: The policy_time of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._policy_time

    @policy_time.setter
    def policy_time(self, policy_time):
        """
        Sets the policy_time of this TimeFlowStDetailInfosOutputDto.
        策略时长（分钟）。

        :param policy_time: The policy_time of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._policy_time = policy_time

    @property
    def remain_flow(self):
        """
        Gets the remain_flow of this TimeFlowStDetailInfosOutputDto.
        剩余流量。

        :return: The remain_flow of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._remain_flow

    @remain_flow.setter
    def remain_flow(self, remain_flow):
        """
        Sets the remain_flow of this TimeFlowStDetailInfosOutputDto.
        剩余流量。

        :param remain_flow: The remain_flow of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._remain_flow = remain_flow

    @property
    def remain_time(self):
        """
        Gets the remain_time of this TimeFlowStDetailInfosOutputDto.
        剩余时长。

        :return: The remain_time of this TimeFlowStDetailInfosOutputDto.
        :rtype: str
        """
        return self._remain_time

    @remain_time.setter
    def remain_time(self, remain_time):
        """
        Sets the remain_time of this TimeFlowStDetailInfosOutputDto.
        剩余时长。

        :param remain_time: The remain_time of this TimeFlowStDetailInfosOutputDto.
        :type: str
        """

        self._remain_time = remain_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TimeFlowStDetailInfosOutputDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
