# coding: utf-8

"""
    上网时长流量策略

    上网时长流量策略编辑查询开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient
from .gettoken_api import GetTokenApi


class TimeFlowConfigApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        # config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            print('api_client cannot be None.')
            # if not config.api_client:
            #     config.api_client = ApiClient()
            # self.api_client = config.api_client

    def add_time_flow_config(self, body, **kwargs):
        """
        新增计费策略
        ## 操作场景 ##  提供新增计费策略北向接口。 ## 接口功能 ##  为指定的租户的站点新增计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.add_time_flow_config(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param TimeFlowConfigCommon body: 计费信息。 (required)
        :return: TimeFlowConfigsOutputDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.add_time_flow_config_with_http_info(body, **kwargs)
        else:
            (data) = self.add_time_flow_config_with_http_info(body, **kwargs)
            return data

    def add_time_flow_config_with_http_info(self, body, **kwargs):
        """
        新增计费策略
        ## 操作场景 ##  提供新增计费策略北向接口。 ## 接口功能 ##  为指定的租户的站点新增计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.add_time_flow_config_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param TimeFlowConfigCommon body: 计费信息。 (required)
        :return: TimeFlowConfigsOutputDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_time_flow_config" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_time_flow_config`")


        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/controller/campus/v1/authconfigservice/accessconfig/timeflowconfig', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='TimeFlowConfigsOutputDto',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def del_time_flow_config(self, body, **kwargs):
        """
        删除计费策略
        ## 操作场景 ##  提供删除计费策略北向接口。 ## 接口功能 ##  为指定的租户的站点删除计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.del_time_flow_config(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param TimeFlowConfigDeleteDto body: 删除条件，策略ID列表。 (required)
        :return: DeleteTimeFlowConfigOutputDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.del_time_flow_config_with_http_info(body, **kwargs)
        else:
            (data) = self.del_time_flow_config_with_http_info(body, **kwargs)
            return data

    def del_time_flow_config_with_http_info(self, body, **kwargs):
        """
        删除计费策略
        ## 操作场景 ##  提供删除计费策略北向接口。 ## 接口功能 ##  为指定的租户的站点删除计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.del_time_flow_config_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param TimeFlowConfigDeleteDto body: 删除条件，策略ID列表。 (required)
        :return: DeleteTimeFlowConfigOutputDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method del_time_flow_config" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `del_time_flow_config`")


        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/controller/campus/v1/authconfigservice/accessconfig/timeflowconfig/batch-delete', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='DeleteTimeFlowConfigOutputDto',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_time_flow_config(self, site_id, **kwargs):
        """
        查询计费策略
        ## 操作场景 ##  提供查询计费策略北向接口。 ## 接口功能 ##  查询计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_time_flow_config(site_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str site_id: 站点ID，UUID格式。 (required)
        :param str id: 计费策略ID，UUID格式。
        :param str time_flow_name: 计费策略名称，模糊查询。
        :return: TimeFlowConfigsOutputDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_time_flow_config_with_http_info(site_id, **kwargs)
        else:
            (data) = self.get_time_flow_config_with_http_info(site_id, **kwargs)
            return data

    def get_time_flow_config_with_http_info(self, site_id, **kwargs):
        """
        查询计费策略
        ## 操作场景 ##  提供查询计费策略北向接口。 ## 接口功能 ##  查询计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_time_flow_config_with_http_info(site_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str site_id: 站点ID，UUID格式。 (required)
        :param str id: 计费策略ID，UUID格式。
        :param str time_flow_name: 计费策略名称，模糊查询。
        :return: TimeFlowConfigsOutputDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['site_id', 'id', 'time_flow_name']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_time_flow_config" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'site_id' is set
        if ('site_id' not in params) or (params['site_id'] is None):
            raise ValueError("Missing the required parameter `site_id` when calling `get_time_flow_config`")

        if 'time_flow_name' in params and len(params['time_flow_name']) > 128:
            raise ValueError("Invalid value for parameter `time_flow_name` when calling `get_time_flow_config`, length must be less than or equal to `128`")
        if 'time_flow_name' in params and len(params['time_flow_name']) < 1:
            raise ValueError("Invalid value for parameter `time_flow_name` when calling `get_time_flow_config`, length must be greater than or equal to `1`")

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))
        if 'time_flow_name' in params:
            query_params.append(('timeFlowName', params['time_flow_name']))
        if 'site_id' in params:
            query_params.append(('siteId', params['site_id']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/controller/campus/v1/authconfigservice/accessconfig/timeflowconfig', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='TimeFlowConfigsOutputDto',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def modify_time_flow_config(self, id, body, **kwargs):
        """
        修改计费策略
        ## 操作场景 ##  提供修改计费策略北向接口。 ## 接口功能 ##  为指定的租户的站点修改计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.modify_time_flow_config(id, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str id: 修改条件，计费策略ID。 (required)
        :param TimeFlowConfigCommon body: 修改内容。 (required)
        :return: CommonTimeFlowConfigDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.modify_time_flow_config_with_http_info(id, body, **kwargs)
        else:
            (data) = self.modify_time_flow_config_with_http_info(id, body, **kwargs)
            return data

    def modify_time_flow_config_with_http_info(self, id, body, **kwargs):
        """
        修改计费策略
        ## 操作场景 ##  提供修改计费策略北向接口。 ## 接口功能 ##  为指定的租户的站点修改计费策略。 ## 接口约束 ##  该接口支持北向管理员访问，必须在用户会话建立后使用。  
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.modify_time_flow_config_with_http_info(id, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str id: 修改条件，计费策略ID。 (required)
        :param TimeFlowConfigCommon body: 修改内容。 (required)
        :return: CommonTimeFlowConfigDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method modify_time_flow_config" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `modify_time_flow_config`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `modify_time_flow_config`")


        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/controller/campus/v1/authconfigservice/accessconfig/timeflowconfig/{id}', 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CommonTimeFlowConfigDto',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
