# Generated by Django 3.1 on 2021-03-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_id', models.CharField(max_length=20, unique=True, verbose_name='设备id')),
                ('terminal_num', models.IntegerField(verbose_name='终端数量')),
                ('up_rate', models.IntegerField(verbose_name='上行速率')),
                ('down_rate', models.IntegerField(verbose_name='下行速率')),
                ('rate_unit', models.CharField(max_length=10, verbose_name='速率单位')),
            ],
        ),
        migrations.CreateModel(
            name='SiteFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=20, unique=True, verbose_name='站点id')),
                ('user_num_2_4', models.IntegerField(verbose_name='2.4G用户数量')),
                ('user_num_5', models.IntegerField(verbose_name='5G用户数量')),
                ('up_rate', models.IntegerField(verbose_name='上行速率')),
                ('down_rate', models.IntegerField(verbose_name='下行速率')),
                ('rate_unit', models.CharField(max_length=10, verbose_name='速率单位')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('hash_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='哈希密码')),
                ('contact_details', models.CharField(max_length=12, verbose_name='联系方式')),
                ('contact_email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('contact_address', models.CharField(max_length=100, verbose_name='客户地址')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=20, unique=True, verbose_name='站点id')),
                ('site_name', models.CharField(max_length=20, verbose_name='站点名称')),
                ('site_address', models.CharField(max_length=100, verbose_name='站点地址')),
                ('billing_level', models.IntegerField(verbose_name='计费等级')),
                ('demand_num', models.IntegerField(verbose_name='需求数量')),
                ('demand_1', models.CharField(max_length=20, verbose_name='需求1')),
                ('demand_2', models.CharField(max_length=20, verbose_name='需求2')),
                ('demand_3', models.CharField(max_length=20, verbose_name='需求3')),
                ('status', models.IntegerField(verbose_name='订单、部署状态')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUAWEI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_id', models.CharField(max_length=20, unique=True, verbose_name='设备id')),
                ('eq_name', models.CharField(max_length=20, verbose_name='设备名称')),
                ('eq_status', models.IntegerField(verbose_name='设备状态')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUAWEI.site')),
            ],
        ),
    ]
