# Generated by Django 3.1 on 2021-03-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0002_auto_20210315_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eq_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='设备id'),
        ),
        migrations.AlterField(
            model_name='equipmentflow',
            name='eq_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='设备id'),
        ),
        migrations.AlterField(
            model_name='site',
            name='demand_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='需求1'),
        ),
        migrations.AlterField(
            model_name='site',
            name='demand_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='需求2'),
        ),
        migrations.AlterField(
            model_name='site',
            name='demand_3',
            field=models.CharField(blank=True, max_length=20, verbose_name='需求3'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='站点id'),
        ),
        migrations.AlterField(
            model_name='site',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteflow',
            name='site_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='站点id'),
        ),
    ]
