# Generated by Django 3.1 on 2021-04-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0003_auto_20210424_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdata',
            name='generate_time',
            field=models.DateTimeField(),
        ),
    ]
