# Generated by Django 3.1 on 2021-03-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0003_auto_20210316_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_class',
            field=models.IntegerField(default=0),
        ),
    ]
