# Generated by Django 3.1 on 2021-04-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0004_auto_20210424_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdata',
            name='generate_time',
            field=models.IntegerField(verbose_name='时间戳'),
        ),
    ]
