# Generated by Django 3.1 on 2021-03-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0004_user_permission_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission_class',
        ),
    ]
