# Generated by Django 3.1 on 2021-04-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0005_remove_user_permission_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
