# Generated by Django 3.1 on 2021-04-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0005_auto_20210424_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='total_down',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='total_up',
        ),
    ]
