# Generated by Django 3.1 on 2021-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='eq_name',
            field=models.CharField(default='', max_length=50, verbose_name='设备名'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='question_type',
            field=models.IntegerField(default=0, verbose_name='问题类型'),
        ),
    ]
