# Generated by Django 3.1 on 2021-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0009_auto_20210506_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='eq_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='设备名'),
        ),
    ]
