# Generated by Django 3.1 on 2021-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0010_auto_20210506_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_details',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='邮箱'),
        ),
    ]
