# Generated by Django 3.1 on 2021-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0011_auto_20210507_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
    ]
