# Generated by Django 3.1 on 2021-04-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0012_auto_20210413_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteflow',
            name='site',
        ),
        migrations.AddField(
            model_name='equipment',
            name='flow_data',
            field=models.CharField(default='', max_length=1000, verbose_name='流量数据'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rate_unit',
            field=models.CharField(default='byte', max_length=10, verbose_name='速率单位'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_down',
            field=models.IntegerField(default=0, verbose_name='下行总流量'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_up',
            field=models.IntegerField(default=0, verbose_name='上行总流量'),
        ),
        migrations.AddField(
            model_name='site',
            name='flow_data',
            field=models.CharField(default='', max_length=1000, verbose_name='流量数据'),
        ),
        migrations.AddField(
            model_name='site',
            name='rate_unit',
            field=models.CharField(default='byte', max_length=10, verbose_name='速率单位'),
        ),
        migrations.AddField(
            model_name='site',
            name='total_down',
            field=models.IntegerField(default=0, verbose_name='下行总流量'),
        ),
        migrations.AddField(
            model_name='site',
            name='total_up',
            field=models.IntegerField(default=0, verbose_name='上行总流量'),
        ),
        migrations.DeleteModel(
            name='EquipmentFlow',
        ),
        migrations.DeleteModel(
            name='SiteFlow',
        ),
    ]
