# Generated by Django 3.1 on 2021-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUAWEI', '0013_auto_20210413_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='manager_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='运营工程师'),
        ),
        migrations.AddField(
            model_name='site',
            name='manager_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='network_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='网络工程师'),
        ),
        migrations.AddField(
            model_name='site',
            name='network_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
